name: sklearn-env
channels:
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0
  - appnope
  - asttokens=2.0.5
  - attrs=23.1.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - blas
  - bleach=4.1.0
  - bokeh=2.4.3
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - cffi=1.15.1
  - click=8.1.3
  - cloudpickle=2.1.0
  - colorama=0.4.6
  - cryptography=41.0.7
  - cycler=0.11.0
  - cytoolz=0.11.2
  - dask=2022.6.1
  - dask-core=2022.6.1
  - dask-glm=0.2.0
  - dask-ml=2022.5.27
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2022.6.1
  - entrypoints=0.4
  - executing=0.8.3
  - fonttools=4.37.0
  - freetype=2.12.1
  - fsspec=2022.8.2
  - heapdict=1.0.1
  - idna=3.3
  - ipykernel=6.15.2
  - ipython=8.4.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.1.0
  - jpeg=9e
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter_client=7.3.5
  - jupyter_core=4.10.0
  - jupyterlab_pygments=0.2.2
  - kiwisolver=1.4.4
  - lcms2=2.12
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcxx=16.0.6
  - libdeflate=1.13
  - libffi=3.4.2
  - libgfortran
  - libgfortran5=11.3.0
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libopenblas=0.3.21
  - libpng
  - libsodium=1.0.18
  - libsqlite=3.39.2
  - libtiff
  - libwebp-base=1.2.4
  - libxcb
  - libxgboost=1.6.1
  - libzlib
  - llvm-openmp=14.0.4
  - llvmlite=0.38.1
  - locket=1.0.0
  - lz4=4.0.0
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mistune=2.0.4
  - msgpack-python=1.0.4
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - nbclient=0.5.13
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - ncurses
  - nest-asyncio=1.5.5
  - numba
  - numexpr=2.8.3
  - numpy
  - openjpeg=2.5.0
  - openssl=3.2.1
  - packaging=21.3
  - pandas=1.4.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.3.0
  - patsy=0.5.4
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.2.2
  - prompt-toolkit=3.0.20
  - psutil=5.9.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-xgboost=1.6.1
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=23.3.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.10.6
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python_abi=3.10
  - pytz=2022.1
  - pyyaml=6.0
  - pyzmq=23.2.0
  - readline=8.1.2
  - referencing=0.30.2
  - rpds-py=0.10.6
  - scikit-learn=1.1.2
  - scipy=1.9.0
  - seaborn
  - seaborn-base
  - setuptools=65.3.0
  - six=1.16.0
  - slicer=0.0.7
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - stack_data=0.2.0
  - statsmodels=0.14.0
  - tbb=2021.5.0
  - tblib=1.7.0
  - threadpoolctl=3.1.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - toolz=0.12.0
  - tornado=6.2
  - tqdm=4.66.2
  - traitlets=5.1.1
  - typing_extensions=4.3.0
  - tzdata=2022c
  - unicodedata2=14.0.0
  - urllib3=1.26.11
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zict=2.2.0
  - zlib=1.2.12
  - zstd=1.5.2
