name: selfies-chem-ml
channels:
  - nvidia
  - rapidsai
  - bioconda
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - 'cuda-version>=12.0,<=12.9'
  - 'pytorch=*=*cuda*'
  - jupyterlab 
  - xarray-spatial 
  - graphistry
  - dash
  - nx-cugraph=25.10
  - rdkit
  - pip
  - pandas
  - numpy
  - scikit-learn
  - pytest
  - pubchempy
  - datasets
  - transformers
  - tokenizers
  - huggingface_hub
  - requests
  - pip:
    - selfies
    - accelerate
    - sentencepiece
